name: USK Portal  main Workflow
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying to live server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_SERVER_SSH_HOST }}
          username: ${{ secrets.MAIN_SERVER_SSH_USERNAME }}
          password: ${{ secrets.MAIN_SERVER_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/uskadmin/
            git checkout -f
            git pull
            php artisan migrate --path=database/migrations/version1
            php artisan o:c
